# Generated by Django 4.1.7 on 2023-04-07 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.TextField()),
                ('field_required', models.BooleanField(default=False)),
                ('sequence', models.IntegerField()),
                ('field_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form_Header',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=100)),
                ('form_key', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Field_Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField(null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.form_field')),
            ],
        ),
        migrations.AddField(
            model_name='form_field',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.form_header'),
        ),
    ]
