# Generated by Django 4.1.7 on 2023-04-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_field',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form_field',
            name='field_type',
            field=models.CharField(max_length=100),
        ),
    ]
