# Generated by Django 4.1.7 on 2023-04-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_form_field_field_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_Field',
            new_name='FormField',
        ),
        migrations.RenameModel(
            old_name='Form_Field_Option',
            new_name='FormFieldOption',
        ),
        migrations.RenameModel(
            old_name='Form_Header',
            new_name='FormHeader',
        ),
    ]
