# Generated by Django 4.1.7 on 2023-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_formheader_form_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formheader',
            name='form_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
