# Generated by Django 4.1.7 on 2023-04-18 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_formheader_form_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldsInOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_required', models.BooleanField(default=False)),
                ('field_type', models.CharField(max_length=100)),
                ('fieldsequent', models.IntegerField()),
                ('field_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldoptions', to='main.formfieldoption')),
            ],
        ),
    ]
