# Generated by Django 4.1.7 on 2023-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_formfieldsinoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldsinoption',
            old_name='fieldsequent',
            new_name='fields_sequence',
        ),
        migrations.AlterField(
            model_name='formfieldsinoption',
            name='field_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formfieldsinoption',
            name='field_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formfieldsinoption',
            name='field_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
