# Generated by Django 4.1.7 on 2023-04-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_fieldsequent_formfieldsinoption_fields_sequence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='field',
            new_name='form_header',
        ),
    ]
